"""Restore template files missing from this checkout (was scripts/restore-from-template.sh).

Files the project gitignores -- docs/, some IDE configs -- are never pushed, so
they are absent after a fresh clone. This re-renders the template into a
throwaway worktree and copies back only the files that do not already exist.
Tracked files are never touched.

Usage: python scripts/task.py restore [--yes]
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path

from tasks.console import error, info


def _git(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", *args], cwd=repo, text=True, capture_output=True, check=check)


def _parse_args(argv: list[str]) -> bool | None:
    """True/False for --yes, or None when the caller should stop."""
    assume_yes = False
    for arg in argv:
        if arg in ("-y", "--yes"):
            assume_yes = True
        elif arg in ("-h", "--help"):
            print(__doc__)
            return None
        else:
            error(f"unknown argument: {arg} (use --help for usage)")
            return None
    return assume_yes


def _project_root() -> Path | None:
    """The copier-generated project this is being run from, or None."""
    if shutil.which("git") is None:
        error("git not found on PATH. Install it and re-run.")
        return None
    found = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"], text=True, capture_output=True, check=False
    )
    if found.returncode != 0:
        error("Not inside a git repository. Run this from a project generated by copier.")
        return None
    repo = Path(found.stdout.strip())
    if not (repo / ".copier-answers.yml").is_file():
        error(f"No .copier-answers.yml in {repo}. This only works in a copier-generated project.")
        return None
    return repo


def _missing_files(src: Path, dst: Path) -> list[Path]:
    """Files present under src but not under dst, as paths relative to src."""
    out: list[Path] = []
    for f in sorted(src.rglob("*")):
        if not f.is_file():
            continue
        rel = f.relative_to(src)
        if rel.parts and rel.parts[0] == ".git":
            continue
        if not (dst / rel).exists():
            out.append(rel)
    return out


def _confirm(missing: list[Path], assume_yes: bool) -> bool:
    """Show what would be restored and ask, unless --yes was given."""
    info("Files that would be restored:")
    print()
    for rel in missing:
        print(f"  {rel.as_posix()}")
    print()
    if assume_yes:
        return True
    try:
        reply = input("Restore these files? [y/N] ")
    except EOFError:
        reply = ""
    if reply.strip().lower() in ("y", "yes"):
        return True
    info("Cancelled - no changes made.")
    return False


def _restore(repo: Path, worktree: Path, assume_yes: bool) -> int:
    """Re-render into the worktree, then copy back what the project is missing."""
    info("Re-rendering template (this re-creates gitignored files)")
    rendered = subprocess.run(
        [
            "uv",
            "run",
            "copier",
            "recopy",
            "--skip-answered",
            "--overwrite",
            "--trust",
            "--quiet",
            "--vcs-ref=HEAD",
            ".",
        ],
        cwd=worktree,
        check=False,
    )
    if rendered.returncode != 0:
        error(f"copier recopy failed with exit {rendered.returncode}")
        return rendered.returncode

    missing = _missing_files(worktree, repo)
    if not missing:
        info("Nothing to restore - project already matches the template.")
        return 0
    if not _confirm(missing, assume_yes):
        return 0

    info("Restoring...")
    for rel in missing:
        dest = repo / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(worktree / rel, dest)
    info("Done.")
    return 0


def main(argv: list[str]) -> int:
    """Entry point: [--yes]."""
    assume_yes = _parse_args(argv)
    if assume_yes is None:
        return 0 if any(a in ("-h", "--help") for a in argv) else 1

    repo = _project_root()
    if repo is None:
        return 1

    worktree = Path(tempfile.mkdtemp(prefix="copier-restore-"))
    try:
        info(f"Creating temporary worktree at {worktree}")
        _git(repo, "worktree", "add", "--quiet", str(worktree), "HEAD")
        return _restore(repo, worktree, assume_yes)
    finally:
        _git(repo, "worktree", "remove", "--force", str(worktree), check=False)
        shutil.rmtree(worktree, ignore_errors=True)
